### PR TITLE
Created field for feature image

### PR DESCRIPTION
**Pull request by jetwes**
adds a field for a image upload. adds a migration. adds the field to the fillable property in the model

### CODE REVIEW

**Comment by tobiasla78** [comment]
Hey, thank you for your PR. This is the first time I've ever received a pull request for my own repository

There are some issues with your code:
1. The migration must be a stub file as the plugin requires you to actually publish the migration
2. FileUpload is not imported in SimplePageResource
3. Currently, the image would only be stored but never displayed

But I agree with adding an optional image upload feature.

Thanks for participating 👍

**Comment by jetwes** [comment]
You are absolutely right.

1. added stub
2. fixed
3. added image in view

I didn't added the image in the view because in my case i show the pages in the frontend and just displayed the image over there.

**Comment by jetwes** [comment]
I also added some config options
added base support for language files
updated readme

**Comment by tobiasla78** [comment]
there is a typo in the migration stub filename and then the filename must be added to `getMigrations()` in `FilamentSimplePagesServiceProvider` otherwise it doesn't get published when running `vendor:publish`

then i will continue to test the code

**Comment by jetwes** [comment]
updated

**Pull request merged**
